// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-inquiries.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/audit.ts
async function recordToolCall(ctx, entry) {
  try {
    if (!ctx.isAuthenticated()) return;
    const supabase = supabaseForUser(ctx);
    await supabase.from("mcp_audit_logs").insert({
      user_id: ctx.getUserId(),
      user_email: ctx.getUserEmail() ?? null,
      client_id: ctx.getClientId() ?? null,
      tool_name: entry.tool,
      action: entry.action,
      arguments: entry.args ?? {},
      target_table: entry.targetTable ?? null,
      target_id: entry.targetId ?? null,
      summary: entry.summary ?? null,
      success: entry.success,
      error_message: entry.error ?? null
    });
  } catch {
  }
}

// src/lib/mcp/tools/list-inquiries.ts
var list_inquiries_default = defineTool({
  name: "list_inquiries",
  title: "List contact inquiries",
  description: "List lead/contact form inquiries submitted on the Themyth Agency site, newest first. Optionally filter by status or unread only.",
  inputSchema: {
    status: z.string().optional().describe("Filter by status, e.g. new, contacted, closed."),
    unread_only: z.boolean().optional().describe("Only return inquiries that have not been read."),
    limit: z.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contact_inquiries").select(
      "id, name, email, website, service_interest, revenue_range, budget_range, message, status, read_at, created_at"
    ).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (status) query = query.eq("status", status);
    if (unread_only) query = query.is("read_at", null);
    const { data, error } = await query;
    await recordToolCall(ctx, {
      tool: "list_inquiries",
      action: "read",
      args: { status, unread_only, limit },
      targetTable: "contact_inquiries",
      summary: error ? "Failed to list inquiries" : `Listed ${data?.length ?? 0} inquiries`,
      success: !error,
      error: error?.message
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { inquiries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-inquiry-status.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var update_inquiry_status_default = defineTool2({
  name: "update_inquiry_status",
  title: "Update inquiry status",
  description: "Update the pipeline status of a contact inquiry and optionally mark it as read.",
  inputSchema: {
    inquiry_id: z2.string().describe("The inquiry id (uuid)."),
    status: z2.string().describe("New status, e.g. new, contacted, qualified, closed."),
    mark_read: z2.boolean().optional().describe("Also stamp the inquiry as read.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ inquiry_id, status, mark_read }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const patch = { status };
    if (mark_read) patch.read_at = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabase.from("contact_inquiries").update(patch).eq("id", inquiry_id).select("id, name, email, status, read_at").maybeSingle();
    await recordToolCall(ctx, {
      tool: "update_inquiry_status",
      action: "write",
      args: { inquiry_id, status, mark_read },
      targetTable: "contact_inquiries",
      targetId: inquiry_id,
      summary: error ? "Failed to update inquiry" : data ? `Set status to "${status}"${mark_read ? " and marked read" : ""} for ${data.name}` : "Inquiry not found",
      success: !error && !!data,
      error: error?.message
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Inquiry not found or not accessible." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { inquiry: data }
    };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_conversations_default = defineTool3({
  name: "list_conversations",
  title: "List live chat conversations",
  description: "List live chat conversations from the site widget, most recently active first, with unread counts.",
  inputSchema: {
    unread_only: z3.boolean().optional().describe("Only conversations with unread visitor messages."),
    limit: z3.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("chat_conversations").select("id, name, email, admin_unread_count, last_message_at, created_at").order("last_message_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (unread_only) query = query.gt("admin_unread_count", 0);
    const { data, error } = await query;
    await recordToolCall(ctx, {
      tool: "list_conversations",
      action: "read",
      args: { unread_only, limit },
      targetTable: "chat_conversations",
      summary: error ? "Failed to list conversations" : `Listed ${data?.length ?? 0} conversations`,
      success: !error,
      error: error?.message
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-chat-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_chat_messages_default = defineTool4({
  name: "list_chat_messages",
  title: "Read a chat conversation",
  description: "Read the full message thread of one live chat conversation, oldest first.",
  inputSchema: {
    conversation_id: z4.string().describe("The conversation id (uuid)."),
    limit: z4.number().int().optional().describe("Max messages to return (default 100, max 500).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("chat_messages").select("id, sender, name, message, created_at, read_at").eq("conversation_id", conversation_id).order("created_at", { ascending: true }).limit(Math.min(Math.max(limit ?? 100, 1), 500));
    await recordToolCall(ctx, {
      tool: "list_chat_messages",
      action: "read",
      args: { conversation_id, limit },
      targetTable: "chat_messages",
      targetId: conversation_id,
      summary: error ? "Failed to read conversation" : `Read ${data?.length ?? 0} messages`,
      success: !error,
      error: error?.message
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/reply-to-chat.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var reply_to_chat_default = defineTool5({
  name: "reply_to_chat",
  title: "Reply to a chat conversation",
  description: "Send an admin reply into a live chat conversation. The visitor sees it in the site chat widget. Supports streaming: pass the same stream_id across several calls to append partial text to one live message, then send final=true on the last chunk. Omit stream_id to send a complete message in one call.",
  inputSchema: {
    conversation_id: z5.string().describe("The conversation id (uuid) to reply in."),
    message: z5.string().describe("The reply text, or the next partial chunk when streaming with a stream_id."),
    stream_id: z5.string().optional().describe(
      "Optional stream identifier. Reuse the same value across calls to append chunks to one live message."
    ),
    final: z5.boolean().optional().describe(
      "Marks the streamed message complete. Defaults to true when no stream_id is given, false while streaming."
    )
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ conversation_id, message, stream_id, final }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const chunk = stream_id ? message : message.trim();
    const isFinal = final ?? !stream_id;
    if (!chunk && !isFinal) {
      return { content: [{ type: "text", text: "Message chunk is empty." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const audit = (success, summary, targetId, error2) => recordToolCall(ctx, {
      tool: "reply_to_chat",
      action: "write",
      args: { conversation_id, stream_id, final: isFinal, chars: chunk.length },
      targetTable: "chat_messages",
      targetId: targetId ?? conversation_id,
      summary,
      success,
      error: error2
    });
    if (stream_id) {
      const { data: existing, error: findError } = await supabase.from("chat_messages").select("id, message").eq("conversation_id", conversation_id).eq("stream_id", stream_id).maybeSingle();
      if (findError) {
        await audit(false, "Failed to look up streamed message", null, findError.message);
        return { content: [{ type: "text", text: findError.message }], isError: true };
      }
      if (existing) {
        const merged = `${existing.message}${chunk}`;
        const { data: data2, error: error2 } = await supabase.from("chat_messages").update({ message: merged, is_streaming: !isFinal }).eq("id", existing.id).select("id, sender, message, is_streaming, created_at").maybeSingle();
        if (error2) {
          await audit(false, "Failed to append stream chunk", existing.id, error2.message);
          return { content: [{ type: "text", text: error2.message }], isError: true };
        }
        await audit(
          true,
          isFinal ? "Completed streamed reply to visitor" : "Appended streamed reply chunk",
          existing.id
        );
        return {
          content: [{ type: "text", text: JSON.stringify(data2, null, 2) }],
          structuredContent: { message: data2, streaming: !isFinal }
        };
      }
    }
    const { data, error } = await supabase.from("chat_messages").insert({
      conversation_id,
      sender: "admin",
      name: "Themyth Agency",
      message: chunk,
      stream_id: stream_id ?? null,
      is_streaming: !isFinal
    }).select("id, sender, message, is_streaming, created_at").maybeSingle();
    if (error) {
      await audit(false, "Failed to send reply", null, error.message);
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    await audit(
      true,
      stream_id ? "Started streamed reply to visitor" : "Sent reply to visitor",
      data?.id ?? null
    );
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { message: data, streaming: !isFinal }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "njtocboidgilrwinmzez";
var mcp_default = defineMcp({
  name: "themyth-growth-studio",
  title: "Themyth Growth Studio",
  version: "0.1.0",
  instructions: "Tools for the Themyth Agency site. Read and triage contact-form inquiries, read live chat conversations, and reply to visitors. All tools act as the signed-in admin user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_inquiries_default, update_inquiry_status_default, list_conversations_default, list_chat_messages_default, reply_to_chat_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
